-- MySQL Script generated by MySQL Workbench
-- Sun Feb 23 18:45:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BIBLIOTECA2` DEFAULT CHARACTER SET utf8 ;
USE `BIBLIOTECA2` ;

-- -----------------------------------------------------
-- Table `mydb`.`Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BIBLIOTECA2`.`Autores` ;

CREATE TABLE IF NOT EXISTS `BIBLIOTECA2`.`Autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BIBLIOTECA2`.`Libros` ;

CREATE TABLE IF NOT EXISTS `BIBLIOTECA2`.`Libros` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `título` VARCHAR(45) NOT NULL,
  `año de publicacion` VARCHAR(45) NULL,
  `categoría` VARCHAR(45) NULL,
  `Autores_id_autor` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  INDEX `fk_Libros_Autores1_idx` (`Autores_id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Autores1`
    FOREIGN KEY (`Autores_id_autor`)
    REFERENCES `BIBLIOTECA2`.`Autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BIBLIOTECA2`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `BIBLIOTECA2`.`Usuarios` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_registro` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRÉSTAMOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BIBLIOTECA2`.`PRÉSTAMOS` ;

CREATE TABLE IF NOT EXISTS `BIBLIOTECA2`.`PRÉSTAMOS` (
  `idPRÉSTAMOS` INT NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  `id_libro` VARCHAR(45) NOT NULL,
  `fecha_entrega` VARCHAR(45) NOT NULL,
  `fecha_devolucion` VARCHAR(45) NOT NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  `Libros_id_libro` INT NOT NULL,
  PRIMARY KEY (`idPRÉSTAMOS`),
  INDEX `fk_PRÉSTAMOS_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_PRÉSTAMOS_Libros1_idx` (`Libros_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_PRÉSTAMOS_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `BIBLIOTECA2`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRÉSTAMOS_Libros1`
    FOREIGN KEY (`Libros_id_libro`)
    REFERENCES `BIBLIOTECA2`.`Libros` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
